### PR TITLE
modernize cmake.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
@pdebuyl @fhoefling please have a look at this PR and the two other open PRs.

**Comment by fhoefling** [comment]
Thanks for the update!

Two questions: Why is CMake ≥ 3.10 required? Wouldn't 3.1 do it as well? Second, the language "C" should not be needed. We link against C libraries, but we don't compile C object code (using gcc instead of g++). So it's all pure C++.

**Comment by KaiSzuttor** [comment]
>  Why is CMake ≥ 3.10 required? Wouldn't 3.1 do it as well?

You are probably right, it was just the version I tested it with. Will check.

> Second, the language "C" should not be needed. We link against C libraries, but we don't compile C object code (using gcc instead of g++). So it's all pure C++.

Yes, but there seems to be a regression in the cmake logic of hdf5. So without enabling the C language, you will get the following error message with recent cmake versions.

``` bash
CMake Error at .local/lib/python3.6/site-packages/cmake/data/share/cmake-3.17/Modules/FindHDF5.cmake:226 (try_compile):
  Unknown extension ".c" for file

   h5xx/build/CMakeFiles/hdf5/cmake_hdf5_test.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX
```

**Comment by fhoefling** [comment]
I see. Can you please add a brief comment to the CMake script that the  
FindHDF5 needs "C" to be enabled?

Also, in the commit message it would be good to include the error message.

The new C++ variables were introduced in CMake 3.1, so it should be  
sufficient to trust the docs blindly and lower the minimum number.
https://cmake.org/cmake/help/v3.1/variable/CMAKE_CXX_STANDARD.html

Can you please make these modifications? Then I'll merge it.

Thanks, Felix

**Comment by KaiSzuttor** [comment]
done

**Pull request merged**
